version: '3.8'

services:
  app:
    build:
      context: .
      platforms:
        - linux/amd64
    container_name: telegram_bot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: test
    depends_on:
      - mysql_hse
      - minio

  mysql_hse:
    image: mysql:8
    container_name: mysql_hse
    environment:
      MYSQL_ROOT_PASSWORD: hse_root_password  # Пароль для root
      MYSQL_USER: hse_user                    # Пользователь
      MYSQL_PASSWORD: hse_password            # Пароль для пользователя
      MYSQL_DATABASE: hse_database
      TZ: "Europe/Moscow"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql_data/data
    platform: linux/amd64

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console Port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    platform: linux/amd64

volumes:
  mysql_data:
    driver: local
  minio_data:
    driver: local
