spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hse_database
    username: hse_user
    password: hse_password
  jpa:
    hibernate:
      ddl-auto: update

  telegram:
    bot:
      username: hscc_hse_bot
      token: 8113684980:AAFEpEsQFkf9SDYV50rLG6X7It9aVM43Bfs
      path: false

  minio:
    url: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: pictures

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

#  quartz:
#    job-store-type: jdbc
#    jdbc:
#      initialize-schema: always
#    properties:
#      org:
#        quartz:
#          jobStore:
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#  quartz:
#    job-store-type: memory
#    scheduler:
#      auto-startup: true
#      instance-name: NotificationScheduler
#    properties:
#      org:
#        quartz:
#          threadPool:
#            threadCount: 5
#
#logging:
#  level:
#    org:
#      quartz: DEBUG
#      hibernate:
#        SQL: DEBUG
#        type: TRACE

image:
  maxSizeHorizontal: 900
  maxSizeHeight: 900
  maxSizeSquare: 900