spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3308/hse_database
    username: hse_user
    password: hse_password

  telegram:
    bot:
      username: hscc_test_bot
      token: 7697397427:AAEblENgSu7YhfxlnfVlPTlqyIwwdp-HNo4
      path: false

  minio:
    url: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: pictures

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: false

#для тестирования в локальных docker контейнерах
---
spring:

  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://mysql_hse:3306/hse_database
#    url: jdbc:postgresql://postgres:5432/hse_database

  minio:
    url: http://minio:9000

  liquibase:
    enabled: true

#для итогового релиза на сервер
---
spring:

  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  datasource:
    url: jdbc:mysql://mysql_hse:3306/hse_database
    username: hse_user
    password: hse_password
#    url: jdbc:postgresql://postgres:5432/hse_database

  telegram:
    bot:
      username: hscc_hse_bot
      token: 8113684980:AAFEpEsQFkf9SDYV50rLG6X7It9aVM43Bfs
      path: false

  minio:
    url: http://minio:9000

  liquibase:
    enabled: true