spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hse_database
    username: hse_user
    password: hse_password
  jpa:
    hibernate:
      ddl-auto: update

  telegram:
    bot:
      username: hscc_hse_bot
      token: 8113684980:AAFEpEsQFkf9SDYV50rLG6X7It9aVM43Bfs
      path: false

  minio:
    url: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: pictures