spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3308/hse_database?serverTimezone=Europe/Moscow
    username: hse_user
    password: SnQWpR

  telegram:
    bot:
      username: hscc_test_bot
      token: 7697397427:AAEblENgSu7YhfxlnfVlPTlqyIwwdp-HNo4
      path: false

  minio:
    url: http://localhost:9000
    accessKey: minioadmin
    secretKey: FOeeCmCq
    bucketName: pictures

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: false

evironment:
  before-save-wait-time: 2000
  notification-before-hour-send: 24
  event-descruction-after-hour: 24
  registration-starts-before-hour: 24
  max-name-length: 120
  max-description-length: 840
  max-location-length: 70
  admin-password: 6v4jww

#для тестирования в локальных docker контейнерах
---
spring:

  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://mysql_hse:3306/hse_database?serverTimezone=Europe/Moscow

  minio:
    url: http://minio:9000

  liquibase:
    enabled: true

#для итогового релиза на сервер
---
spring:

  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  datasource:
    url: jdbc:mysql://mysql_hse:3306/hse_database?serverTimezone=Europe/Moscow
#    username: hse_user
#    password: SnQWpR

  telegram:
    bot:
      username: hscc_hse_bot
      token: 8113684980:AAFEpEsQFkf9SDYV50rLG6X7It9aVM43Bfs
      path: false

  minio:
    url: http://minio:9000

  liquibase:
    enabled: true