package org.example.entity;

public enum UserState {
    //start states
    START,

    //base user registration
    ENTERING_FIRSTNAME,
    ENTERING_LASTNAME,
    ENTERING_STUDY_PLACE,

    //admin registration
    CHOOSING_ROLE,
    ENTERING_SPECIAL_KEY,

    //shared states
    COMMAND_CHOOSING,

    //ADMIN STATES
    //new event
    ENTERING_EVENT_NAME,
    ENTERING_EVENT_DESCRIPTION,
    ENTERING_EVENT_PICTURE,
    ENTERING_EVENT_START_TIME,
    CHOOSING_EVENT_DURATION,
    ENTERING_EVENT_LOCATION,
    ACCEPTING_SAVE_NEW_EVENT,
    //edit event
    ACCEPTING_EDITING_EVENT_NAME,
    EDITING_EVENT_NAME,
    ACCEPTING_EDITING_EVENT_DESCRIPTION,
    EDITING_EVENT_DESCRIPTION,
    ACCEPTING_EDITING_EVENT_PICTURE,
    EDITING_EVENT_PICTURE,
    ACCEPTING_EDITING_EVENT_START_TIME,
    EDITING_EVENT_START_TIME,
    ACCEPTING_EDITING_EVENT_DURATION,
    EDITING_EVENT_DURATION,
    ACCEPTING_EDITING_EVENT_LOCATION,
    EDITING_EVENT_LOCATION,
    ACCEPTING_SAVE_EDITED_EVENT,
    //forward message to all
    ACCEPTING_FORWARD_MESSAGE_TO_ALL,
    //forward message to event subscribers
    ACCEPTING_FORWARD_MESSAGE_TO_EVENT_SUBSCRIBERS
}
